development:
  adapter: postgresql
  encoding: unicode
  database: email_poll_development
  host: localhost
  pool: 5
  username: ericaporter
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: email_poll_test
  host: localhost
  pool: 5
  username: ericaporter
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: email_poll_production
  host: localhost
  pool: 5
  username: ericaporter
  password:
cucumber:
  <<: *test